### ISSUE TITLE
希望编译下桂电的osx的二进制

### ISSUE THREAD

**Issue by leftjs** [xuzhipengnt/ipclient_gxnu#2]
平常不玩qt 希望师兄顺手把桂电gui给编译了吧...

**Comment by xuzhipengnt** [comment]
能否提供握手的数据包？最好是Linux下的握手包

**Comment by leftjs** [comment]
数据包不会截取，我用师兄的ipclient的python版， 把server改成桂电的172.16.1.1后能够拨号成功，就是看不到金额等等信息... 
![image](https://cloud.githubusercontent.com/assets/8311633/20088790/80102a9a-a5bd-11e6-8fdd-5870b77889f6.png)

**Comment by xuzhipengnt** [comment]
已经编译，ipclient_gui_guet_win32_binary.exe，你测试一下

**Comment by leftjs** [comment]
![image](https://cloud.githubusercontent.com/assets/8311633/20243350/d57e4eec-a98e-11e6-81ac-c50b4acd3002.png)
师兄，桂电gui测试可用，可以抓一抓剩余金额来解析下，这样就没人用官方的了，哈哈 :-)

**Comment by leftjs** [comment]
![image](https://cloud.githubusercontent.com/assets/8311633/20243358/38fee0d0-a98f-11e6-9d59-1819c95118cc.png)
桂电gui 一切正常，金额显示正常，谢谢师兄，我帮你在学校推广下，哈哈哈  👍
